game:
  title: "Minimal Test Game"

window:
  width: 640
  height: 480

player:
  name: "TestHero"
  sprite_path: "test_minimal_game/assets/sprites/hero.png"
  sprite:
    frame_width: 32
    frame_height: 32
    columns: 4
    rows: 1

assets:
  scenes: ["test_minimal_game/scenes/*.yaml"]

start_scene: "test_room"