version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "point-click-engine/maintainers"
    assignees:
      - "point-click-engine/maintainers"
      
  # Keep Crystal dependencies up to date (when Dependabot supports Crystal)
  # This is a placeholder for future Crystal support in Dependabot
  # - package-ecosystem: "crystal"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: "deps"
  #     include: "scope"