game:
  title: "Engine Test"

window:
  width: 1280
  height: 720
  target_fps: 120

display:
  scaling_mode: "PixelPerfect"
  target_width: 640
  target_height: 480

player:
  name: "Hero"
  sprite_path: "assets/hero.png"
  sprite:
    frame_width: 64
    frame_height: 64
    columns: 8
    rows: 4
  start_position:
    x: 100.0
    y: 200.0

features:
  - verbs
  - portraits
  - debug

settings:
  debug_mode: true
  show_fps: true
  log_player_input: false
  master_volume: 0.8
  music_volume: 0.7
  sfx_volume: 0.9