game:
  title: "UI Test"

ui:
  hints:
    - text: "Welcome to the game!"
      duration: 2.0
    - text: "Press I for inventory"
      duration: 3.0
  opening_message: "The adventure begins..."

start_scene: "intro"