name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a scene with...
        2. Add a character...
        3. Call method...
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: crystal
      placeholder: |
        require "point_click_engine"
        
        # Your code here
        
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Ubuntu/Linux
        - Windows (WSL)
        - Other Linux
        - Windows (native)
    validations:
      required: true
      
  - type: input
    id: crystal-version
    attributes:
      label: Crystal Version
      description: What version of Crystal are you running?
      placeholder: "1.16.3"
    validations:
      required: true
      
  - type: input
    id: engine-version
    attributes:
      label: Engine Version
      description: What version of the Point & Click Engine are you using?
      placeholder: "0.3.0"
    validations:
      required: true
      
  - type: input
    id: raylib-version
    attributes:
      label: Raylib Version
      description: What version of Raylib do you have installed?
      placeholder: "5.5.0"
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
    validations:
      required: false