name: Feature Request
description: Suggest an idea for the Point & Click Engine
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to be able to...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I also considered...
    validations:
      required: false
      
  - type: dropdown
    id: module
    attributes:
      label: Which module would this affect?
      description: Select the module(s) this feature would primarily affect
      multiple: true
      options:
        - Core Engine
        - Graphics/Display
        - Characters/NPCs
        - Scenes/Hotspots
        - Inventory System
        - UI/Dialogs
        - AI Behaviors
        - YAML/Serialization
        - Examples/Documentation
        - Build System
        - Other/Multiple
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Simple (few lines of code)"
        - "Medium (new method/class)"
        - "Complex (significant changes)"
        - "Major (architectural changes)"
        - "Not sure"
    validations:
      required: false
      
  - type: textarea
    id: usage
    attributes:
      label: Usage Example
      description: Provide a code example of how this feature would be used
      render: crystal
      placeholder: |
        # Example usage
        engine = PointClickEngine::Engine.new(800, 600, "My Game")
        # ... your new feature usage
        
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Needed for project"
        - "Critical - Blocking development"
    validations:
      required: true
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I can help implement this feature
        - label: I can help test this feature
        - label: I can help document this feature
        - label: I can provide code examples
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false