# Temporarily disabled due to dependency issues
# name: Documentation
# 
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# 
# jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          mesa-common-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          xorg-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          build-essential
          
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1.8.2
      with:
        crystal: latest
        
    - name: Cache shards
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/shards
          lib
        key: ${{ runner.os }}-shards-${{ hashFiles('shard.lock') }}
        restore-keys: |
          ${{ runner.os }}-shards-
          
    - name: Install dependencies
      run: shards install
      
    - name: Generate documentation
      run: crystal docs --output=docs
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true