# Temporarily disabled due to tool availability
# name: Security
# 
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   schedule:
#     # Run security checks weekly
#     - cron: '0 10 * * 1'
# 
# jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1.8.2
      with:
        crystal: latest
        
    - name: Check for security issues in dependencies
      run: |
        echo "Checking for known security vulnerabilities..."
        # Crystal doesn't have a built-in security audit tool yet
        # This is a placeholder for future security scanning
        shards check
        
    - name: Scan for hardcoded secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
        
    - name: Check file permissions
      run: |
        echo "Checking file permissions..."
        find . -type f -perm /o+w -not -path "./.git/*" | while read file; do
          echo "Warning: World-writable file found: $file"
        done